from sqlalchemy.sql import text

from app.models import SCHEMA, Garment, db, environment


# Adds a demo user, you can add other users here if you want
def seed_garments():
    for garment in [
        {
            "user_id": 1,
            "title": "Emerald Green Utility Jacket",
            "price": 129.99,
            "discounted_price": 89.99,
            "description": "Stay stylish and warm with our Emerald Green Utility Jacket. Crafted from durable, water-resistant fabric, this jacket features a sleek, streamlined design with multiple pockets for added functionality. The adjustable drawstring waist and ribbed cuffs ensure a perfect fit, while the rich green color adds a pop of color to any outfit. Ideal for both casual outings and outdoor adventures.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 1,
            "title": "Frosted Gray & White Windbreaker",
            "price": 99.99,
            "discounted_price": 69.99,
            "description": "Embrace sleek, modern style with the Frosted Gray & White Windbreaker. Designed for both function and fashion, this jacket features a lightweight, breathable material that's perfect for layering. The clean white base is complemented by dynamic gray accents and reflective detailing, ensuring visibility and a trendy look. With a full zip closure, adjustable hood, and elastic cuffs, it provides both comfort and protection against the elements. Perfect for urban commutes or casual outings.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 1,
            "title": "Noir Splash Graphic Jacket",
            "price": 119.99,
            "discounted_price": 84.99,
            "description": "Make a bold statement with the Noir Splash Graphic Jacket. Featuring a sleek black base with striking white splashes, this jacket combines edgy design with practical functionality. Crafted from high-quality, water-resistant fabric, it offers both comfort and protection. The full-zip front, adjustable hood, and ribbed cuffs ensure a snug fit, while the unique graphic pattern adds a touch of artistic flair. Ideal for those who want to stand out while staying warm.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 1,
            "title": "Crimson Bold Jacket",
            "price": 109.99,
            "discounted_price": 79.99,
            "description": "Stand out in style with the Crimson Bold Jacket. This vibrant red jacket is designed to make a statement, featuring a sleek, modern cut and high-quality, durable fabric. With its full-zip front, adjustable hood, and cozy fleece lining, it offers both warmth and versatility. The bold red color ensures you’ll be noticed, whether you’re hitting the streets or heading out for an adventure. Perfect for adding a pop of color to any outfit.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 2,
            "title": "Classic Blue Denim Jacket",
            "price": 89.99,
            "discounted_price": 64.99,
            "description": "Embrace timeless style with the Classic Blue Denim Jacket. Made from high-quality, durable denim, this jacket features a classic cut with a modern twist. The medium blue wash adds a vintage feel, while the button-front closure and chest pockets provide both functionality and flair. Perfect for layering over tees or shirts, it’s a versatile wardrobe staple that seamlessly combines comfort and style. Ideal for casual outings or adding a rugged edge to your look.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 2,
            "title": "Charcoal Classic Hoodie",
            "price": 69.99,
            "discounted_price": 49.99,
            "description": "Elevate your casual wardrobe with the Charcoal Classic Hoodie. Crafted from soft, high-quality cotton blend, this hoodie provides ultimate comfort and warmth. Featuring a classic design with a spacious kangaroo pocket, adjustable drawstring hood, and ribbed cuffs, it's perfect for lounging or layering. The versatile charcoal gray color makes it easy to pair with any outfit, while the durable fabric ensures it stands up to everyday wear.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 2,
            "title": "White & Black Stripe Sport Jacket",
            "price": 119.99,
            "discounted_price": 89.99,
            "description": "Step up your style game with the White & Black Stripe Sport Jacket. This sleek jacket features a crisp white base with a bold black stripe running along the shoulders and sleeves, creating a striking contrast. Made from lightweight, breathable material, it’s perfect for both active and casual wear. The full-zip front, zippered pockets, and adjustable hem offer practicality and a tailored fit. Whether you’re hitting the gym or the streets, this jacket combines performance with a touch of modern sophistication.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 2,
            "title": "Navy Essentials Jacket",
            "price": 99.99,
            "discounted_price": 74.99,
            "description": "Discover timeless style and practicality with the Navy Essentials Jacket. Crafted from premium, water-resistant fabric, this jacket features a classic navy color that’s both versatile and sophisticated. With a full-zip front, adjustable hood, and multiple pockets, it combines function with a sleek design. The lightweight yet insulating material makes it perfect for layering throughout the year, while the clean lines and subtle detailing ensure a polished look. Ideal for everyday wear or casual outings.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 3,
            "title": "Light Blue & Red Dual-Tone Raincoat",
            "price": 139.99,
            "discounted_price": 99.99,
            "description": "Brighten up rainy days with the Light Blue & Red Dual-Tone Raincoat. Featuring a refreshing light blue base with bold red accents, this raincoat combines vibrant colors with functional design. Made from waterproof, breathable fabric, it offers excellent protection from the elements while remaining comfortable and lightweight. The adjustable hood, elastic cuffs, and snap-button front ensure a customizable fit, while the stylish color block pattern adds a modern touch to your rainy day attire.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 3,
            "title": "Pure White Cozy Hoodie",
            "price": 74.99,
            "discounted_price": 54.99,
            "description": "Stay effortlessly stylish and comfortable with the Pure White Cozy Hoodie. Made from a soft, high-quality cotton blend, this hoodie features a classic design with a plush fleece lining that provides warmth without bulk. The spacious kangaroo pocket, adjustable drawstring hood, and ribbed cuffs ensure a relaxed fit that’s perfect for lounging or layering. The clean white color makes it a versatile addition to any wardrobe, offering a crisp, fresh look that pairs with virtually anything.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 3,
            "title": "Sunbeam Light Yellow Hoodie",
            "price": 69.99,
            "discounted_price": 49.99,
            "description": "Brighten up your wardrobe with the Sunbeam Light Yellow Hoodie. Crafted from a soft, cozy cotton blend, this hoodie features a cheerful light yellow color that adds a splash of sunshine to any outfit. Designed with a relaxed fit, it includes a spacious kangaroo pocket, an adjustable drawstring hood, and ribbed cuffs for comfort and practicality. Perfect for lounging at home or casual outings, this hoodie combines warmth with a touch of cheerful style.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 3,
            "title": "Midnight Black Leather Jacket",
            "price": 249.99,
            "discounted_price": 179.99,
            "description": "Elevate your style with the Midnight Black Leather Jacket. This premium jacket is crafted from genuine leather, offering both durability and a luxurious feel. The sleek black finish, zippered front, and classic silhouette create a timeless look that pairs effortlessly with any outfit. Features include a comfortable quilted lining, multiple zippered pockets, and adjustable cuffs for a tailored fit. Perfect for adding a touch of edge to your wardrobe or making a bold statement on any occasion.",
            "inventory": 10,
            "category": "MEN",
        },
        {
            "user_id": 1,
            "title": "Urban Black Women's Puffy Jacket",
            "price": 139.99,
            "discounted_price": 99.99,
            "description": "Stay warm and stylish with the Urban Black Women's Puffy Jacket. Designed with both comfort and fashion in mind, this jacket features a sleek black exterior with a plush, insulating fill that provides superior warmth without the bulk. The streamlined design includes a full-zip front, adjustable hood, and elasticized cuffs to keep the cold out. Multiple zippered pockets offer practicality, while the flattering silhouette enhances your figure. Ideal for cold weather outings or adding a touch of sophistication to your winter wardrobe.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 1,
            "title": "Blush Pink Women’s Shirt",
            "price": 49.99,
            "discounted_price": 34.99,
            "description": "Add a touch of elegance to your wardrobe with the Blush Pink Women’s Button-Down Shirt. This shirt is crafted from soft, breathable fabric that drapes beautifully and ensures all-day comfort. The subtle blush pink color adds a fresh, feminine touch, while the classic button-down design, with a collared neck and long sleeves, offers a timeless look suitable for both professional and casual settings. Finished with a tailored fit and a sleek, streamlined silhouette, this shirt pairs effortlessly with trousers, skirts, or jeans.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 1,
            "title": "Cocoa Comfort Sports Bra",
            "price": 34.99,
            "discounted_price": 24.99,
            "description": "Experience both style and support with the Cocoa Comfort Sports Bra. This sports bra features a soft, stretchy fabric in a versatile light brown shade, ideal for layering or wearing on its own. Designed for medium support, it includes a wide underband and adjustable straps for a secure, customizable fit. The moisture-wicking material ensures you stay dry and comfortable during workouts, while the sleek, minimal design adds a touch of understated elegance. Perfect for yoga, jogging, or everyday wear.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 1,
            "title": "Elegant Burgundy A-Line Dress",
            "price": 119.99,
            "discounted_price": 89.99,
            "description": "Embrace sophistication with the Elegant Burgundy A-Line Dress. This dress features a rich burgundy hue that exudes elegance and class. Crafted from a luxurious, flowy fabric, it drapes beautifully and moves with you. The A-line silhouette flatters a variety of body shapes, while the fitted bodice and subtle pleating at the waist create a timeless, graceful look. With a knee-length cut and a hidden zipper in the back, this dress is perfect for formal events, special occasions, or an evening out.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 2,
            "title": "Fuchsia Elegance Women's Top",
            "price": 59.99,
            "discounted_price": 44.99,
            "description": "Add a vibrant splash of color to your wardrobe with the Fuchsia Elegance Women's Top. This top features a striking dark pink shade that brings a bold, modern flair to any outfit. Crafted from a soft, breathable fabric, it offers both comfort and style with its relaxed fit and flattering cut. The top includes elegant details such as a subtle V-neckline, delicate pleats along the shoulders, and a slightly curved hem that adds a touch of sophistication. Perfect for pairing with jeans or a skirt for a chic, everyday look.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 2,
            "title": "Autumn Ember Women's Sweater",
            "price": 79.99,
            "discounted_price": 59.99,
            "description": "Embrace the warmth of fall with the Autumn Ember Women's Sweater. This cozy sweater features a rich dark orange hue that adds a vibrant, seasonal touch to your wardrobe. Made from a soft, medium-weight knit, it offers both comfort and warmth. The sweater includes a classic crew neckline, ribbed cuffs and hem, and a relaxed fit that layers effortlessly over any outfit. Perfect for cool autumn days or layering on chilly winter evenings, this sweater combines style and comfort seamlessly.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 2,
            "title": "Ivory Soft Neck Women's Sweater",
            "price": 89.99,
            "discounted_price": 64.99,
            "description": "Elevate your essentials with the Ivory Soft Neck Women's Sweater. This elegant sweater features a pristine white color and a luxurious, soft knit that ensures all-day comfort. The standout detail is its cozy, oversized cowl neck, which adds a touch of sophistication and extra warmth. The relaxed fit and ribbed cuffs and hem create a flattering silhouette that pairs beautifully with both casual and dressier outfits. Ideal for layering during cooler months, this sweater combines classic style with modern comfort.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 2,
            "title": "Polka Dot Charm Black Sundress",
            "price": 89.99,
            "discounted_price": 64.99,
            "description": "Embrace a playful yet sophisticated look with the Polka Dot Charm Black Sundress. Featuring a classic black base adorned with white spots, this sundress combines fun polka dot patterns with a flattering A-line silhouette. Made from lightweight, breathable fabric, it’s perfect for warm weather outings or summer events. The dress includes adjustable spaghetti straps, a cinched waist, and a flared skirt that enhances your figure while providing comfort and ease of movement. Ideal for casual gatherings, beach days, or brunch with friends.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 3,
            "title": "Blush Pink Tiered Sundress",
            "price": 99.99,
            "discounted_price": 74.99,
            "description": "Celebrate sunny days in style with the Blush Pink Tiered Sundress. This charming sundress features a soft, blush pink color that exudes a feminine and fresh vibe. The dress is designed with a tiered skirt for a playful, flowy look and includes adjustable straps for a customizable fit. Made from a lightweight, breathable fabric, it ensures comfort and ease throughout the day. The fitted bodice and gathered waist provide a flattering silhouette, making it perfect for garden parties, casual outings, or a day at the beach.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 3,
            "title": "Scarlet Grace Women's Top",
            "price": 54.99,
            "discounted_price": 39.99,
            "description": "Add a vibrant touch to your wardrobe with the Scarlet Grace Women's Top. This eye-catching red top features a flattering, relaxed fit that drapes beautifully. Crafted from a soft, lightweight fabric, it offers both comfort and a chic silhouette. The top includes a classic scoop neckline, short sleeves, and a subtle high-low hem that adds a modern twist. Perfect for pairing with jeans, skirts, or trousers, this versatile piece is ideal for both casual outings and dressed-up occasions.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 3,
            "title": "Noir Essential Crop Top",
            "price": 39.99,
            "discounted_price": 29.99,
            "description": "Embrace versatile style with the Noir Essential Crop Top. This sleek black crop top features a fitted design made from a soft, stretchy fabric that provides a comfortable and flattering fit. The top includes a classic crew neckline and short sleeves, making it perfect for layering or wearing on its own. Its minimalist design pairs effortlessly with high-waisted jeans, skirts, or shorts, offering a chic look for both casual and semi-formal occasions. Ideal for adding a touch of sophistication to any outfit.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 3,
            "title": "Classic Black Women's Sweater",
            "price": 79.99,
            "discounted_price": 59.99,
            "description": "Elevate your wardrobe essentials with the Classic Black Women's Sweater. This timeless piece is crafted from a soft, high-quality knit that provides both warmth and comfort. Featuring a versatile black color, it pairs effortlessly with any outfit. The sweater includes a relaxed fit, crew neckline, and ribbed cuffs and hem for a polished look. Perfect for layering during cooler months or wearing on its own, this sweater combines style and practicality for a chic, everyday choice.",
            "inventory": 10,
            "category": "WOMEN",
        },
        {
            "user_id": 1,
            "title": "Sky Blue Kids' Hoodie",
            "price": 39.99,
            "discounted_price": 29.99,
            "description": "Keep your little one cozy and stylish with the Sky Blue Kids' Hoodie. Made from a soft, durable cotton blend, this hoodie offers both comfort and warmth for everyday wear. The vibrant blue color adds a cheerful touch, while the classic design includes a spacious kangaroo pocket, an adjustable drawstring hood, and ribbed cuffs for a snug fit. Perfect for school, playdates, or lounging at home, this hoodie is a versatile addition to any child's wardrobe.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 1,
            "title": "Midnight Black Kids' Hoodie",
            "price": 39.99,
            "discounted_price": 29.99,
            "description": "Keep your child warm and stylish with the Midnight Black Kids' Hoodie. Crafted from a soft, cozy cotton blend, this hoodie provides exceptional comfort and durability. The classic black color makes it versatile and easy to pair with any outfit. Featuring a spacious kangaroo pocket, an adjustable drawstring hood, and ribbed cuffs, it offers a perfect fit for active kids. Ideal for school, sports, or casual outings, this hoodie is a must-have staple for any young wardrobe.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 1,
            "title": "Kaleidoscope Kids' Hoodie",
            "price": 49.99,
            "discounted_price": 37.99,
            "description": "Brighten up your child’s day with the Kaleidoscope Kids' Hoodie. This fun and vibrant hoodie features a dynamic mix of colors in a playful pattern that’s sure to delight. Made from a soft, high-quality cotton blend, it ensures comfort and warmth for all-day wear. The hoodie includes a cozy, adjustable drawstring hood, a roomy kangaroo pocket for essentials, and ribbed cuffs for a snug fit. Perfect for school, outdoor play, or weekend outings, this hoodie combines eye-catching style with practical design.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 1,
            "title": "Forest Green Kids' Jumper",
            "price": 49.99,
            "discounted_price": 37.99,
            "description": "Keep your child cozy and stylish with the Forest Green Kids' Jumper. Made from a soft, breathable knit, this jumper features a rich green color that’s both vibrant and versatile. The design includes a classic crew neckline, long sleeves with ribbed cuffs, and a relaxed fit for comfort and easy movement. Perfect for layering during cooler weather, this jumper pairs well with jeans, leggings, or shorts, making it a great addition to any child's wardrobe.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 2,
            "title": "Green & Navy Color-Block Kids' Jacket",
            "price": 39.99,
            "discounted_price": 29.99,
            "description": "Add a touch of style and fun to your child's wardrobe with the Green & Navy Color-Block Kids' Jacket. This eye-catching jacket features a dynamic color-block design with vibrant green on one side and classic navy on the other. Crafted from durable, water-resistant fabric, it provides protection and comfort in various weather conditions. The jacket includes a full-zip front, an adjustable hood, and elastic cuffs for a snug fit. Perfect for school, outdoor activities, or weekend adventures, this jacket combines practical functionality with playful design.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 2,
            "title": "Golden Oak Kids' Jacket",
            "price": 79.99,
            "discounted_price": 59.99,
            "description": "Illuminate your child's wardrobe with the Golden Oak Kids' Jacket. This jacket features a stunning goldish-brown hue that adds a touch of warmth and sophistication. Made from a soft, durable fabric with a cozy, insulated lining, it offers both comfort and protection against cooler weather. The jacket includes a full-zip front, an adjustable hood, and elastic cuffs to ensure a snug fit. Perfect for school, outdoor activities, or casual outings, it combines practical functionality with a unique and stylish look.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 2,
            "title": "Classic Denim Kids' Coat",
            "price": 89.99,
            "discounted_price": 67.99,
            "description": "Elevate your child’s style with the Classic Denim Kids' Coat. This timeless coat is crafted from high-quality denim with a durable, soft finish. Featuring a classic blue wash, it includes a button-front closure, functional chest pockets, and adjustable cuffs for a customizable fit. The coat’s relaxed fit and slightly longer length provide extra coverage and comfort. Perfect for layering over tees or sweaters, it’s an ideal choice for school, playdates, or weekend outings, combining classic denim style with practical design.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 2,
            "title": "Ocean Blue Kids' Sweater",
            "price": 49.99,
            "discounted_price": 37.99,
            "description": "Brighten up your child's wardrobe with the Ocean Blue Kids' Sweater. This vibrant blue sweater is made from a soft, cozy knit that offers both comfort and warmth for everyday wear. Featuring a classic crew neckline, long sleeves, and ribbed cuffs and hem, it ensures a snug, comfortable fit. The rich blue color makes it a versatile piece that pairs well with jeans, shorts, or skirts. Perfect for layering during cooler days or wearing on its own, this sweater combines style and practicality for a playful yet polished look.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 3,
            "title": "Navy Comfort Kids' Sweatshirt",
            "price": 44.99,
            "discounted_price": 34.99,
            "description": "Keep your child cozy and stylish with the Navy Comfort Kids' Sweatshirt. Made from a soft, brushed fleece, this sweatshirt provides exceptional warmth and comfort. The classic navy color is both versatile and timeless, making it easy to pair with any outfit. Featuring a crew neckline, ribbed cuffs and hem, and a relaxed fit, it ensures a snug, comfortable wear. Ideal for school, playdates, or lounging at home, this sweatshirt combines durability with a classic design for everyday use.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 3,
            "title": "Midnight Blue Kids' Zip Jacket",
            "price": 59.99,
            "discounted_price": 44.99,
            "description": "Elevate your child's outerwear collection with the Midnight Blue Kids' Zip Jacket. This sleek jacket features a deep, rich blue color and is crafted from a durable, water-resistant fabric that provides protection and comfort. The full-zip front allows for easy layering, while the adjustable hood and elastic cuffs ensure a snug fit. With its practical design and classic style, this jacket is perfect for school, outdoor activities, or casual outings. The versatile color and functional features make it a must-have addition to any kid’s wardrobe.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 3,
            "title": "Onyx Black Kids' Jacket",
            "price": 64.99,
            "discounted_price": 49.99,
            "description": "Keep your child warm and stylish with the Onyx Black Kids' Jacket. This classic black jacket is crafted from a durable, water-resistant fabric that offers excellent protection against the elements. Designed with a full-zip front, adjustable hood, and elastic cuffs, it ensures a comfortable and secure fit. The jacket features a soft, insulated lining for added warmth and practicality. Ideal for everyday wear, school, or outdoor activities, this versatile jacket combines timeless style with functional design.",
            "inventory": 10,
            "category": "KIDS",
        },
        {
            "user_id": 3,
            "title": "Striped Night Kids' Jacket",
            "price": 69.99,
            "discounted_price": 52.99,
            "description": "Add a touch of sporty style to your child's wardrobe with the Striped Night Kids' Jacket. This sleek black jacket features a bold white stripe running down the sleeves, creating a dynamic, modern look. Made from a durable, water-resistant fabric, it provides reliable protection against the elements while ensuring comfort. The jacket includes a full-zip front, adjustable hood, and elastic cuffs for a snug fit. With its eye-catching design and practical features, it's perfect for school, sports, or casual outings.",
            "inventory": 10,
            "category": "KIDS",
        },
    ]:
        db.session.add(Garment(**garment))
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_garments():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.garments RESTART IDENTITY CASCADE;"
        )
    else:
        db.session.execute(text("DELETE FROM garments"))

    db.session.commit()
