from sqlalchemy.sql import text
from werkzeug.security import generate_password_hash

from app.models import SCHEMA, User, db, environment


# Adds a demo user, you can add other users here if you want
def seed_users():
    for user in [
        {
            "first_name": "Demo",
            "last_name": "User",
            "email": "demo@aa.io",
            "username": "demouser",
            "hashed_password": generate_password_hash("password"),
        },
        {
            "first_name": "Dane",
            "last_name": "Kirsch",
            "email": "dkirsch0@furl.net",
            "username": "dkirsch0",
            "hashed_password": generate_password_hash("tA4>cvTya`x|$,"),
        },
        {
            "first_name": "Guilbert",
            "last_name": "Jakubovsky",
            "email": "gjakubovsky1@digg.com",
            "username": "gjakubovsky1",
            "hashed_password": generate_password_hash("uG6|E}$=Rq"),
        },
        # Men
        {
            "first_name": "John",
            "last_name": "Doe",
            "email": "john.doe@example.com",
            "username": "johndoe",
            "hashed_password": generate_password_hash("tX3+53l#8v`&{)"),
        },
        {
            "first_name": "Michael",
            "last_name": "Smith",
            "email": "michael.smith@example.com",
            "username": "michaels",
            "hashed_password": generate_password_hash("qX8e*yX~g66HHjI"),
        },
        {
            "first_name": "David",
            "last_name": "Johnson",
            "email": "david.johnson@example.com",
            "username": "davidj",
            "hashed_password": generate_password_hash("xM6}GTBk8Z'sW~"),
        },
        {
            "first_name": "James",
            "last_name": "Brown",
            "email": "james.brown@example.com",
            "username": "jamesb",
            "hashed_password": generate_password_hash("gM9.vL1n"),
        },
        {
            "first_name": "Robert",
            "last_name": "Taylor",
            "email": "robert.taylor@example.com",
            "username": "robertt",
            "hashed_password": generate_password_hash("nL6%>%R`Y3NC"),
        },
        {
            "first_name": "Daniel",
            "last_name": "Wilson",
            "email": "daniel.wilson@example.com",
            "username": "danielw",
            "hashed_password": generate_password_hash("iN6#N/_.13VsN"),
        },
        {
            "first_name": "Matthew",
            "last_name": "Moore",
            "email": "matthew.moore@example.com",
            "username": "matthewm",
            "hashed_password": generate_password_hash("eP1<.)Ho66y8Eq"),
        },
        {
            "first_name": "Joseph",
            "last_name": "Anderson",
            "email": "joseph.anderson@example.com",
            "username": "josepha",
            "hashed_password": generate_password_hash("tX7{icsB*sZp/Z"),
        },
        {
            "first_name": "Ethan",
            "last_name": "Thomas",
            "email": "ethan.thomas@example.com",
            "username": "ethant",
            "hashed_password": generate_password_hash("kL1/{L3bV3"),
        },
        {
            "first_name": "William",
            "last_name": "Taylor",
            "email": "william.taylor@example.com",
            "username": "williamt",
            "hashed_password": generate_password_hash("xC9}yM8i"),
        },
        {
            "first_name": "Alexander",
            "last_name": "Lee",
            "email": "alexander.lee@example.com",
            "username": "alexanderl",
            "hashed_password": generate_password_hash("bU3|QbQ**w"),
        },
        {
            "first_name": "Henry",
            "last_name": "Harris",
            "email": "henry.harris@example.com",
            "username": "henryh",
            "hashed_password": generate_password_hash("eZ3<_oX%`b"),
        },
        {
            "first_name": "Jack",
            "last_name": "Clark",
            "email": "jack.clark@example.com",
            "username": "jackc",
            "hashed_password": generate_password_hash("pI5?_Uj5}a"),
        },
        {
            "first_name": "Lucas",
            "last_name": "Lewis",
            "email": "lucas.lewis@example.com",
            "username": "lucasl",
            "hashed_password": generate_password_hash("gD9,682d%>g"),
        },
        {
            "first_name": "Owen",
            "last_name": "Walker",
            "email": "owen.walker@example.com",
            "username": "owenw",
            "hashed_password": generate_password_hash("uG4`6Aq/=@o"),
        },
        {
            "first_name": "Sebastian",
            "last_name": "Hall",
            "email": "sebastian.hall@example.com",
            "username": "sebastianh",
            "hashed_password": generate_password_hash("lW5asgIUd"),
        },
        {
            "first_name": "David",
            "last_name": "Adams",
            "email": "david.adams@example.com",
            "username": "davidad",
            "hashed_password": generate_password_hash("nF8}f!+`HBF4"),
        },
        {
            "first_name": "Gabriel",
            "last_name": "Mitchell",
            "email": "gabriel.mitchell@example.com",
            "username": "gabrielm",
            "hashed_password": generate_password_hash("jS2@lK<9,v"),
        },
        {
            "first_name": "Ryan",
            "last_name": "Scott",
            "email": "ryan.scott@example.com",
            "username": "ryans",
            "hashed_password": generate_password_hash("dY1#bi~m"),
        },
        {
            "first_name": "James",
            "last_name": "Rodriguez",
            "email": "james.rodriguez@example.com",
            "username": "jamesr",
            "hashed_password": generate_password_hash("vR2}H>~Fo|"),
        },
        {
            "first_name": "Eli",
            "last_name": "Morgan",
            "email": "eli.morgan@example.com",
            "username": "elim",
            "hashed_password": generate_password_hash("hJ4**73/NH+>Y!G"),
        },
        {
            "first_name": "Leo",
            "last_name": "Cox",
            "email": "leo.cox@example.com",
            "username": "leoc",
            "hashed_password": generate_password_hash("rW7,(rpmO"),
        },
        {
            "first_name": "Caleb",
            "last_name": "Gray",
            "email": "caleb.gray@example.com",
            "username": "calebg",
            "hashed_password": generate_password_hash("fW0\FBgcY>uXW$"),
        },
        {
            "first_name": "Isaiah",
            "last_name": "James",
            "email": "isaiah.james@example.com",
            "username": "isaiahj",
            "hashed_password": generate_password_hash("vT3!e(K~ebxm"),
        },
        # Women
        {
            "first_name": "Emma",
            "last_name": "Davis",
            "email": "emma.davis@example.com",
            "username": "emmad",
            "hashed_password": generate_password_hash("jW0*z=pU&"),
        },
        {
            "first_name": "Olivia",
            "last_name": "Garcia",
            "email": "olivia.garcia@example.com",
            "username": "oliviag",
            "hashed_password": generate_password_hash("lT7%IQ2_.g98Q{3"),
        },
        {
            "first_name": "Ava",
            "last_name": "Martinez",
            "email": "ava.martinez@example.com",
            "username": "avam",
            "hashed_password": generate_password_hash("nV2@+g'9WWrhD|(n"),
        },
        {
            "first_name": "Isabella",
            "last_name": "Rodriguez",
            "email": "isabella.rodriguez@example.com",
            "username": "isabellar",
            "hashed_password": generate_password_hash("pZ5@~i_bVN`wpM"),
        },
        {
            "first_name": "Sophia",
            "last_name": "Wilson",
            "email": "sophia.wilson@example.com",
            "username": "sophiaw",
            "hashed_password": generate_password_hash("nZ6=#_vI+zU'(7"),
        },
        {
            "first_name": "Charlotte",
            "last_name": "Lopez",
            "email": "charlotte.lopez@example.com",
            "username": "charlottel",
            "hashed_password": generate_password_hash("vG8<,<bNR3%"),
        },
        {
            "first_name": "Amelia",
            "last_name": "Gonzalez",
            "email": "amelia.gonzalez@example.com",
            "username": "amelia",
            "hashed_password": generate_password_hash("qA3!Iav*j"),
        },
        {
            "first_name": "Mia",
            "last_name": "Perez",
            "email": "mia.perez@example.com",
            "username": "miap",
            "hashed_password": generate_password_hash("kM9}bWjnrntI'rq"),
        },
        {
            "first_name": "Harper",
            "last_name": "White",
            "email": "harper.white@example.com",
            "username": "harperw",
            "hashed_password": generate_password_hash("qW0(T`)5>"),
        },
        {
            "first_name": "Evelyn",
            "last_name": "Harris",
            "email": "evelyn.harris@example.com",
            "username": "evelynh",
            "hashed_password": generate_password_hash("uO8}guM8W<"),
        },
        {
            "first_name": "Ella",
            "last_name": "Brown",
            "email": "ella.brown@example.com",
            "username": "ellab",
            "hashed_password": generate_password_hash("kT3)w,bINB"),
        },
        {
            "first_name": "Abigail",
            "last_name": "Young",
            "email": "abigail.young@example.com",
            "username": "abigaily",
            "hashed_password": generate_password_hash("mO4)}k{'61!"),
        },
        {
            "first_name": "Scarlett",
            "last_name": "King",
            "email": "scarlett.king@example.com",
            "username": "scarlettk",
            "hashed_password": generate_password_hash("eS3/0+U0Bx"),
        },
        {
            "first_name": "Grace",
            "last_name": "Scott",
            "email": "grace.scott@example.com",
            "username": "graces",
            "hashed_password": generate_password_hash("qK0%{10`\)bd$,`w"),
        },
        {
            "first_name": "Chloe",
            "last_name": "Adams",
            "email": "chloe.adams@example.com",
            "username": "chloea",
            "hashed_password": generate_password_hash("dU6!#}Jy>/nA2D"),
        },
        {
            "first_name": "Camila",
            "last_name": "Baker",
            "email": "camila.baker@example.com",
            "username": "camilab",
            "hashed_password": generate_password_hash("tE5.Pm&aYb~ZeO"),
        },
        {
            "first_name": "Aria",
            "last_name": "Nelson",
            "email": "aria.nelson@example.com",
            "username": "arian",
            "hashed_password": generate_password_hash("qS8~+u|L'\H@"),
        },
        {
            "first_name": "Avery",
            "last_name": "Carter",
            "email": "avery.carter@example.com",
            "username": "averyc",
            "hashed_password": generate_password_hash("hH9,4lCErsf{"),
        },
        {
            "first_name": "Lily",
            "last_name": "Mitchell",
            "email": "lily.mitchell@example.com",
            "username": "lilym",
            "hashed_password": generate_password_hash("aK2~Cr(,"),
        },
        {
            "first_name": "Sofia",
            "last_name": "Perez",
            "email": "sofia.perez@example.com",
            "username": "sofiap",
            "hashed_password": generate_password_hash("yW4.dD)`&xY5'c3Y"),
        },
        {
            "first_name": "Hannah",
            "last_name": "Ward",
            "email": "hannah.ward@example.com",
            "username": "hannahw",
            "hashed_password": generate_password_hash("wE0>hKgCSMG)f$9"),
        },
        {
            "first_name": "Ellie",
            "last_name": "Cook",
            "email": "ellie.cook@example.com",
            "username": "elliec",
            "hashed_password": generate_password_hash("lD9<Tk%WFxxZo"),
        },
        {
            "first_name": "Natalie",
            "last_name": "Cook",
            "email": "natalie.cook@example.com",
            "username": "nataliec",
            "hashed_password": generate_password_hash("wD8}m^Lp7!X@"),
        },
        {
            "first_name": "Zoe",
            "last_name": "Murphy",
            "email": "zoe.murphy@example.com",
            "username": "zoem",
            "hashed_password": generate_password_hash("eR4)F+z6Qx!"),
        },
        # Parents
        {
            "first_name": "Emily",
            "last_name": "Miller",
            "email": "emily.miller@example.com",
            "username": "emilym",
            "hashed_password": generate_password_hash("bP8!_?pYl$c+9"),
        },
        {
            "first_name": "Michael",
            "last_name": "Davis",
            "email": "michael.davis@example.com",
            "username": "michaeld",
            "hashed_password": generate_password_hash("vW8>e{EVfX"),
        },
        {
            "first_name": "Lisa",
            "last_name": "Taylor",
            "email": "lisa.taylor@example.com",
            "username": "lisat",
            "hashed_password": generate_password_hash("gM7>#T?{s"),
        },
        {
            "first_name": "James",
            "last_name": "Williams",
            "email": "james.williams@example.com",
            "username": "jamesw",
            "hashed_password": generate_password_hash("dK5}e3|)a"),
        },
        {
            "first_name": "Sarah",
            "last_name": "Jones",
            "email": "sarah.jones@example.com",
            "username": "sarahj",
            "hashed_password": generate_password_hash("nB8'ySp7P"),
        },
        {
            "first_name": "David",
            "last_name": "Miller",
            "email": "david.miller@example.com",
            "username": "davidm",
            "hashed_password": generate_password_hash("tD0~Y!~Q9%"),
        },
        {
            "first_name": "Jessica",
            "last_name": "Wilson",
            "email": "jessica.wilson@example.com",
            "username": "jessicaw",
            "hashed_password": generate_password_hash("qP8a2Jx"),
        },
        {
            "first_name": "John",
            "last_name": "Brown",
            "email": "john.brown@example.com",
            "username": "johnb",
            "hashed_password": generate_password_hash("vU6_ApZe|cyR"),
        },
        {
            "first_name": "Karen",
            "last_name": "Garcia",
            "email": "karen.garcia@example.com",
            "username": "kareng",
            "hashed_password": generate_password_hash("sF8'l)Zd"),
        },
        {
            "first_name": "Robert",
            "last_name": "Johnson",
            "email": "robert.johnson@example.com",
            "username": "robertj",
            "hashed_password": generate_password_hash("yU2)mg*ktB"),
        },
        {
            "first_name": "Laura",
            "last_name": "Martinez",
            "email": "laura.martinez@example.com",
            "username": "lauram",
            "hashed_password": generate_password_hash("gL8>HgFW"),
        },
        {
            "first_name": "William",
            "last_name": "Anderson",
            "email": "william.anderson@example.com",
            "username": "william",
            "hashed_password": generate_password_hash("fD4=T%<20+"),
        },
        {
            "first_name": "Linda",
            "last_name": "Lee",
            "email": "linda.lee@example.com",
            "username": "lindal",
            "hashed_password": generate_password_hash("wN3}#8XJ9t"),
        },
        {
            "first_name": "Brian",
            "last_name": "Harris",
            "email": "brian.harris@example.com",
            "username": "brianh",
            "hashed_password": generate_password_hash("pV4,@~DB)K_"),
        },
        {
            "first_name": "Jennifer",
            "last_name": "Miller",
            "email": "jennifer.miller@example.com",
            "username": "jenniferm",
            "hashed_password": generate_password_hash("aN93wYNAkXyv{"),
        },
        {
            "first_name": "George",
            "last_name": "Moore",
            "email": "george.moore@example.com",
            "username": "georgem",
            "hashed_password": generate_password_hash("xV4+8>h}S"),
        },
        {
            "first_name": "Elizabeth",
            "last_name": "Taylor",
            "email": "elizabeth.taylor@example.com",
            "username": "elizabetht",
            "hashed_password": generate_password_hash("nU6\?kI#*~cZ."),
        },
        {
            "first_name": "Andrew",
            "last_name": "Jackson",
            "email": "andrew.jackson@example.com",
            "username": "andrewj",
            "hashed_password": generate_password_hash("nH5)aHBtq"),
        },
        {
            "first_name": "Patricia",
            "last_name": "Wilson",
            "email": "patricia.wilson@example.com",
            "username": "patriciaw",
            "hashed_password": generate_password_hash("nU2>DX(3vcg"),
        },
        {
            "first_name": "Steven",
            "last_name": "Thomas",
            "email": "steven.thomas@example.com",
            "username": "stevent",
            "hashed_password": generate_password_hash("nU8}?>_uy>,"),
        },
        {
            "first_name": "Jessica",
            "last_name": "Martinez",
            "email": "jessica.martinez@example.com",
            "username": "jessicam",
            "hashed_password": generate_password_hash("jX5cFeww'"),
        },
        {
            "first_name": "Paul",
            "last_name": "Anderson",
            "email": "paul.anderson@example.com",
            "username": "paula",
            "hashed_password": generate_password_hash("tJ5/s~bk5"),
        },
        {
            "first_name": "Sandra",
            "last_name": "Clark",
            "email": "sandra.clark@example.com",
            "username": "sandrac",
            "hashed_password": generate_password_hash("hO1=2}IV"),
        },
        {
            "first_name": "Austin",
            "last_name": "Gray",
            "email": "austin.gray@example.com",
            "username": "austing",
            "hashed_password": generate_password_hash("wM7^yL9`Rz%"),
        },
    ]:
        db.session.add(User(**user))
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_users():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.users RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM users"))

    db.session.commit()
